### ISSUE TITLE
GCG binaries on Windows

### ISSUE THREAD

**Issue by ghost** [scipopt/PyGCGOpt#11]
Hi Team,

We have noticed that the Windows installer for SCIP Optimization Suite 8.0.0 does not include GCG. Is there a plan to build GCG for Windows and including it in the SCIP Optimization Suite for Windows?

Best,
Steve

**Comment by jurgen-lentz** [comment]
Hey Steve,

Yes, we are planning to improve GCG such that it builds on Windows in the future. We will then also include GCG in the SCIP Optimization Suite for Windows. Unfortunately, we cannot guarantee any deadline but for the meantime we refer here to our [Windows Installation Guide](https://gcg.or.rwth-aachen.de/doc-3.5.0/windows-install.html).

Best wishes,
Jurgen

**Comment by SteveAfterFidelity** [comment]
Jurgen,

Thank you for your quick response.  We'll be watching for the new improvements to GCG that allow it to be built on Windows.  We understand that there is no fxed timetable. 

-Steve

**Comment by jurgen-lentz** [comment]
Steve,

You can build now GCG on windows using the Github mirror of [gcg](https://github.com/scipopt/gcg).

Kind regards,
Jurgen
