### ISSUE TITLE
Accessing GCG from Pyomo package 

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PyGCGOpt#14]
Dear support team,

First of all, thanks so much for your interesting work in developing and maintaining such a solver. I am working on a variant of the parallel machine scheduling problem with the Pyomo package on Google-Colab. By default, everything works well, but when I want to run some moderate problems its default solver, "CBC", cannot execute well. Since I have tried to install SCIP by Pyscipopt package and use the following method to call that. 

```
!conda install --channel conda-forge pyscipopt
...
SolverFactory('scip').solve(m, tee= True).write()
```

It takes around 4 (mins) to solve the problem optimality. As I have worked with Pygcgopt on Colab, I tried to solve the problem within a separate notebook by calling:

```
m = Model("PMSPPC")
m.readProblem("PMSPPC.lp")

m.printVersion()
m.redirectOutput()

m.setMinimize()
m.optimize()
```

The problem was solved in seconds!!! (say less than 20 secs and I think in the default mode). Now, I am willing to call GCG from the Pyomo package. To do this I called that by `!conda install --channel conda-forge pygcgopttried` and the methods like:

```
1) SolverFactory('scipgcg').solve(m, tee= True).write() 
4) SolverFactory('scip-gcg').solve(m, tee= True).write()
2) SolverFactory('gcg').solve(m, tee= True).write()
3) SolverFactory('Pygcgopt ').solve(m, tee= True).write() 
```

But, neither of them can be calling the solver and already throw some errors like:

```
RuntimeError: Attempting to use an unavailable solver.

The SolverFactory was unable to create the solver "scipgcg"
and returned an UnknownSolver object.  This error is raised at the point
where the UnknownSolver object was used as if it were valid (by calling
method "solve").

The original solver was created with the following parameters:
	executable: scipgcg
	type: scipgcg
	_args: ()
	options: {}
```
I was wondering if, How can I call the GCG within Pyomo?

Best regards
Abbas

**Comment by jurgen-lentz** [comment]
Unfortunately, Pyomo does not provide an interface to GCG. As for now, pygcgopt is the only package that can be used to call GCG in python.

**Comment by abb-omidi** [comment]
Dear Jurgen,

Many thanks for your informative comments.

Regards
