### ISSUE TITLE
request for help

### ISSUE THREAD

**Issue by fzu181800330** [scipopt/PyGCGOpt#15]
i am a beginner，My original question is：
subto c3:forall<i> in C2 :             vif sum<j> in C1:a[j]*b[i]*z[j,i] == 0               then C[i] == 0 else C[i] >=0 end;
I want to translate it into a question written in python language：
for i in C2:
    expr = quicksum(a[j] * b[i] * z[(j, i)] for j in C1 if z[(j, i)] == 1)
    if model.isEQ(expr,0):
        model.addCons(C[i] == 0, "c4[%d]" % i)
    else:
        model.addCons(C[i] >= 0, "c4[%d]" % i)

compiler error：
    if model.isEQ(expr,0):
  File "src/pyscipopt/scip.pyx", line 1178, in pyscipopt.scip.Model.isEQ
TypeError: must be real number, not pyscipopt.scip.Expr

how to save this question？？？？

**Comment by jurgen-lentz** [comment]
Is this question related to pyscipopt?

**Comment by jurgen-lentz** [comment]
Issue closed due to inactivity.
