### ISSUE TITLE
Issue to run pygcgopt 

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PyGCGOpt#21]
Dear support team,

Recently, there was an issue on Pyscipopt that could not be reached, but with an update on SCIP, the issue is fixed.
I checked this by Pygcgopt and I found that the issue is still remaining. The following is the output:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[6], line 1
----> 1 from pygcgopt import *

File /opt/conda/lib/python3.10/site-packages/pygcgopt/__init__.py:44
     41 from pyscipopt import SCIP_ROWORIGINTYPE
     43 # export user-relevant objects
---> 44 from pygcgopt.gcg import Model, Detector, PricingSolver
     45 from pygcgopt.gcg import PY_GCG_PRICINGSTATUS as GCG_PRICINGSTATUS

ImportError: libscip.so.8.0: cannot open shared object file: No such file or directory
```

Would you please, check that and say how we can fix it?

All the best
Abbas

**Comment by ytsao** [comment]
I got same error message as well.

**Comment by jurgen-lentz** [comment]
Can you please try to pull the new version of pygcgopt from conda and tell me if the problem still occurs?

**Comment by ytsao** [comment]
@jurgen-lentz , I used PyPI to install pygcgopt instead of conda. Do I need to switch to use conda? In addition, I tried to uninstall pygcgopt (0.2.0) and install pygcgopt (0.3.1). But it still not working. Thanks

**Comment by abb-omidi** [comment]
@jurgen-lentz,

Thank you so much. now, it works fine.

All the best
