### ISSUE TITLE
The issue to visualize the structure of the problem

### ISSUE THREAD

**Issue by abb-omidi** [scipopt/PyGCGOpt#24]
Dear support team,

I am working on some formulations in which I would like to visualize the problem structure. I am trying to run this as shown [here](https://scipopt.github.io/PyGCGOpt/examples/cpmp/cpmp.html#Visualizing-Decompositions).

Also, the code is as follows:

```
from pygcgopt import *
m = Model("Test")
m.readProblem("Test.lp")

m.redirectOutput()
m.printVersion()
m.setMinimize()

m.presolve()
m.detect()
decomps = m.listDecompositions()

for i in range(len(decomps)):
  d = decomps[i]
  print(f"Decomp scores: {d.classicScore=:.04f}, {d.borderAreaScore=:.04f}, {d.maxWhiteScore=:.04f}, {d.maxForWhiteScore=:.04f}")

d

d = decomps[21]
d.isSelected = True
m.setParam('limits/time', 60)
m.optimize()
```

When the problem is run it shows no error, but it cannot provide any visualization of the problem. I was wondering if, how can I fix that?

All the best
Abbas

**Comment by jurgen-lentz** [comment]
Do you execute the code within a jupyter notebook? Do you use conda?

**Comment by abb-omidi** [comment]
@jurgen-lentz,

Thanks for your reply. 
1) I am working with Jupiter notebooks on Google-Colab. 

2) Yes. I installed pygcgopt through Conda. I am not aware of if there are other ways, if so, please let me know. 

Best regards
Abbas

**Comment by abb-omidi** [comment]
@jurgen-lentz,

Would you please say where I am doing wrong and how can I fix this?

Best
Abbas

**Comment by jurgen-lentz** [comment]
Could you try first to write the decomposition d as the last line of the cell first? If this doesn't work make sure that gnuplot is installed in your conda environment.

**Comment by abb-omidi** [comment]
Dear @jurgen-lentz,

Thanks for your informative comments. 
I added  `gnuplot` in my conda environment via `!conda install -y gnuplot` comment. Also, it seems that is necessary to move the decomposition d as the last line of the cell. As the follow-up questions:
1) Do we have to add `from gnuplot import *` like `from pygcgopt import *`?
2) When the problem is solved and before writing the plot the following line is shown:
```
"/tmp/tmp8fkhzkpe/vis.gp" line 1: warning: iconv failed to convert degree sign
"/tmp/tmpshkpy5ch/vis.gp" line 1: warning: iconv failed to convert degree sign
```

![image](https://github.com/scipopt/PyGCGOpt/assets/42294317/b40404e9-bfad-47a4-b710-fb9dcbffaef3)


Would you please, is there any issue to my run?

All the best
Abbas

**Comment by abb-omidi** [comment]
Dear support team,

I hope you are doing well.
Would you please, is it still relevant to get the mentioned warning when I want to show the picture?

```
"/tmp/tmp8fkhzkpe/vis.gp" line 1: warning: iconv failed to convert degree sign
"/tmp/tmpshkpy5ch/vis.gp" line 1: warning: iconv failed to convert degree sign
```

P.S:
GCG version 3.5.5 [GitHash: da78996a]

All the best
Abbas

**Comment by jurgen-lentz** [comment]
The warnings do come from gnuplot. The visualization seems to be alright.

**Comment by jurgen-lentz** [comment]
And you do not need to add `from gnuplot import *`.

**Comment by abb-omidi** [comment]
Dear @jurgen-lentz,

Thanks for your prompt response.

> And you do not need to add from gnuplot import *.


Actually, I did not add this as everything works now well, (I have used Kaggle), but when I added this I got the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 2
      1 from pygcgopt import *
----> 2 from gnuplot import *
      4 model = Model("test")
      5 model.redirectOutput()

ModuleNotFoundError: No module named 'gnuplot'
```

Also, I would really like to use SCIP and GCG on Google- Colab as it is very convenient and can be used for educational purposes, but I cannot find any straightforward way to install GCG and also show the plot there. Do you have any idea of how can we fix that?

P.S: GCG still needs to use Conda and also would not match well with Conda-lab. Indeed Conda cannot be called on the Colab directly nowadays. I have to install Conda first, then install GCG which might cause some incompatible issues.  


All the best
Abbas

**Comment by jurgen-lentz** [comment]
I am not very familiar with Google-Colab but have you tried the following [steps](https://saturncloud.io/blog/how-to-install-conda-package-to-google-colab/)?

**Comment by abb-omidi** [comment]
Dear @jurgen-lentz,

Thanks. I am still using a similar procedure.

Best regards
Abbas

**Comment by jurgen-lentz** [comment]
Have you an idea, how we may help you to improve your experience on google-colab using pygcgopt?

**Comment by abb-omidi** [comment]
Dear @jurgen-lentz,

Many thanks for your attention. As my experiences with GCG are not much and I am somehow new to using that, maybe I cannot say any technical issues that being useful on your side, but I am trying to note something that I have encountered with, and I hope they have not been far from your project scope:

1. To install GCG anyone needs to install so many external packages.
2. The package to install gnuplot actually needs much more time to complete. (takes around 20min!).
3. As Conda is not supported by Google Colab anymore the installed version, by some manipulation, is somewhat old and may cause some difficulties to use this.
4. As you know, SCIP recently updated its package that allows to install that so easily via PIP installation. If it can be done by GCG, would be great. 

Finally thanks once again, and I hope it will be helpful.

All the best 
Abbas 

P.S: The required packages to install GCG (for those who are interested in):

```
!pip install gnuplot_kernel
%load_ext gnuplot_kernel

!pip install condacolab

import condacolab
condacolab.install()

import condacolab
condacolab.check()

!pip install conda
import sys
print(sys.path)
import conda
print(conda.__path__)

# To check some properties 
%%bash
conda info

!conda install --channel conda-forge pygcgopt
!conda install --channel conda-forge gnuplot
!conda install -y conda-forge gnuplot # (in some cases this is needed!)
```

**Comment by jurgen-lentz** [comment]
Thank you for your input! I will close this issue for now.
