### ISSUE TITLE
How to disable the automatic aggregation of sub-problem in GCG?

### ISSUE THREAD

**Issue by weicheng22** [scipopt/PyGCGOpt#33]
Dear support team,

I am using PyGCGOpt 0.3.1 to solve my MIP and have specified a decomposition for my model. However, I noticed that GCG automatically detects isomorphisms in my specified block and aggregates them when possible. How can I disable this automatic aggregation process?

All the best
Regards

**Comment by weicheng22** [comment]
Alright, instead of using the default discretization approach, I utilized the convexification approach in the GCG terminal. Does PyGCGOpt offer a way to set the relaxing parameter?

**Comment by Lichthagel** [comment]
> Alright, instead of using the default discretization approach, I utilized the convexification approach in the GCG terminal. Does PyGCGOpt offer a way to set the relaxing parameter?

You should be able to use `m.setBoolParam("relaxing/gcg/discretization", False)`

**Comment by weicheng22** [comment]
Thank you for your comments!

> > Alright, instead of using the default discretization approach, I utilized the convexification approach in the GCG terminal. Does PyGCGOpt offer a way to set the relaxing parameter?
> 
> You should be able to use `m.setBoolParam("relaxing/gcg/discretization", False)`
