### ISSUE TITLE
concurrentopt crashes with a 'Segmentation fault (core dumped)' error

### ISSUE THREAD

**Issue by weicheng22** [scipopt/PyGCGOpt#34]
Dear Support Team,

I have compiled scipoptsuite-8.1.0 using the GCC compiler (GNU 13.2.0) on Ubuntu 24.04 LTS. For the configuration, I set the CMAKE argument "TPI=tny" in SCIP and enabled "OPENMP: on" in GCG. After compiling, I loaded my problem in MPS format ([my_model.zip](https://github.com/user-attachments/files/16228109/my_model.zip)) and attempted to solve it with SCIP and GCG. While concurrent optimization works in SCIP, GCG crashes with the error "Segmentation fault (core dumped)" as shown in the attached figures.

![2](https://github.com/user-attachments/assets/254d185e-ecb3-4dca-9fb4-5c1b48aea7ac)

![3](https://github.com/user-attachments/assets/9f842592-6c29-4ec7-8f28-b3f6d8e4244b)

I also tried using scipoptsuite-9.1.0, but encountered the same issue. How can I resolve these errors?

Best regards,
Wei

**Comment by mluebbecke** [comment]
Hi Wei, GCG does not support a concurrent mode; essentially because solving the master problem by column generation is a particular implementation of the primal simplex algorithm, and this is all we have. All the best, Marco
